### ISSUE TITLE
import multiresolutionimageinterface as mir doesnt work with python

### ISSUE THREAD

**Issue by malithrukshankg** [malithrukshankg/metastatic#1]
when i import multiresolutionimageinterface using ASAP it gives foolwing error

C:\Users\User\PycharmProjects\untitled\venv\Scripts\python.exe C:/Users/User/PycharmProjects/untitled/test.py
Traceback (most recent call last):
  File "C:\Program Files\ASAP 1.9\bin\multiresolutionimageinterface.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/User/PycharmProjects/untitled/test.py", line 1, in <module>
    import multiresolutionimageinterface as mir
  File "C:\Program Files\ASAP 1.9\bin\multiresolutionimageinterface.py", line 21, in <module>
    _multiresolutionimageinterface = swig_import_helper()
  File "C:\Program Files\ASAP 1.9\bin\multiresolutionimageinterface.py", line 20, in swig_import_helper
    return importlib.import_module('_multiresolutionimageinterface')
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1

i have already add the asap bin folder in PYTHONPATH

**Comment by kilaOoO** [comment]
I also meet the error "ImportError: DLL load failed: The specified module could not be found",Do you solve it?

**Comment by NeginQajari** [comment]
when i import multiresolutionimageinterface using ASAP it gives this error ,Who has solved this problem?
